theme: osuny
_merge: deep
params:
  plausible: cmjnrvb.net
  summary:
    position: hero
  search:
    active: false
  image_sizes:
    sections:
      posts:
        item:
          mobile:   375
          tablet:   600
          desktop:  1100
  debug:
    active: false
    productionUrl: https://www.cmjnrvb.net